// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjkmvskvwmybtiltfyyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqa212c2t2d215YnRpbHRmeXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5Nzg5MzQsImV4cCI6MjA2MzU1NDkzNH0.10kugtbHysm2K541jVxpFOuOY4vWhQBF9jdFtIOkZyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);